<?php
/**
 * Implementation of hook_uc_order();
 */
function uc_user_uc_order($op, $order, $status) {
  switch ($op) {
    case 'update':
      // We might want to add the "Order Status" to the Userpoints Ubercart options...
      if ($order->order_status != 'completed' && ($status == 'completed' && $order->uid > 0) && ($order_user = user_load($order->uid)) !== FALSE) {
        if (is_array($order->products) && count($order->products)) {
			foreach ($order->products as $product) {
			
				if ($product->nid == 139){// for renew registration
					$expires = timetoexpire($order->uid);
					if(isset($product->data['attributes']['roles'])){
						foreach ($product->data['attributes']['roles'] as $key => $value) {
							switch($key){
								case 20: //honarjo option ID
									$rid = 4;
									if ($expires['honarjo'] < 1){
										db_update('uc_roles_expirations')->fields(array('expiration' => time()))->condition('uid', $order->uid)->condition('rid', $rid)->execute();
										// Punch the role into the user object.
										$roles_list = $order_user->roles + array($rid => _uc_roles_get_name($rid));
										$order_user = user_save($order_user, array('roles' => $roles_list));
									}
									break;
								case 21: //vip option ID
									$rid = 6;
									if ($expires['vip'] < 1){
										db_update('uc_roles_expirations')->fields(array('expiration' => time()))->condition('uid', $order->uid)->condition('rid', $rid)->execute();
										// Punch the role into the user object.
										$roles_list = $order_user->roles + array($rid => _uc_roles_get_name($rid));
										$order_user = user_save($order_user, array('roles' => $roles_list));
									}
									break;
								default:
							}
						}
					}
				}
				// mdump($product, true);
				
				if($product->nid == 1086 ){ // registration in online courses
					foreach ($product->data['attributes']['instrument'] as $key=> $value) {

						if(instrument_info('oid', $key, array('name'), 'online') != false){

							add_collection($order_user , instrument_info('oid', $key, array('name'), 'online') , 'l1' , '1');
							
							$field_favorite['und'][0]['value'] =  instrument_info('oid', $key, array('name'), 'online');
							$order_user = user_save($order_user, array('field_favorite' => $field_favorite));
						} else{
							drupal_set_message(t('there is a problem. please contact to support for detail.<br>code : @id , value : @val', array('@id'=> 4 , '@val' => $value ,)), 'error');
						}
						
						if(isset($product->data['attributes']['teacher']) && key($product->data['attributes']['teacher']) ){
							$teacher_oid = key($product->data['attributes']['teacher']);
							$teacher_uid = instrument_info('Teacher_OptionId', $teacher_oid, array('ostad_uid'), 'online');
							if($teacher_uid == false){
								continue; //skip the rest
							}
						} else{
							drupal_set_message(t('there is a problem. please contact to support for detail.<br>code : @id , value : @val', array('@id'=> 6 , '@val' => $value ,)), 'error');
							continue; //skip the rest
						}	

						$type = 1; //for student relationship type for default
						$role = 4;
						$approved = true ;
						if(isset($product->data['attributes']['level'][21]) ){ //vip registration
							$type = 3; //for vip relationship type
							$role = 6;
						}
						
						//im not sure this is the best idea to not give user role in his first week
				        uc_roles_grant($order_user, $role, time() + (1 * 24 * 60 * 60));

						$relationship = user_relationships_request_relationship($order->uid, $teacher_uid , $type , $approved);
						if($relationship === FALSE){
							drupal_set_message(t('there is a problem. please contact to support for detail.<br>code : @id , value : @val', array('@id'=> 5 , '@val' => $value ,)), 'error');
						}
						
						$params = array(
						  'uid' => $order_user->uid,
						  'points' => ($order->order_total * 1), /* ($price * 1.2) شارژ اضافه برای جشنواره*/
						  'operation' => 'ثبت نام اولیه',
						);
						userpoints_userpointsapi($params);
						drupal_set_message('حساب کاربری شما بابت افزودن تمرین شارژ شد.', 'status');
						drupal_goto('/user/'. $order_user->uid);
					}
				}
				
				if ($product->nid == 2597){// for offline registration
					drupal_goto('enrollment/time-selection');
				}
            }  
        }
      }
  }
}

function uc_user_forms($form_id, $args) {
  $forms = array();
//  $users = entity_load('user');
  $users = db_query("SELECT uid from users where uid != 0")->fetchAll();
  foreach($users as $user){
	$forms['student_confirmation_form_'. $user->uid]['callback'] = 'student_confirmation_form';  
	$forms['student_node_refrence_form_'. $user->uid]['callback'] = 'student_node_refrence_form';  
  }
  return $forms;
}

function student_confirmation_form($form, &$form_state, $uid) {
	if (!is_array($form)) {
		$form = array();
	}
	$form['approval'] = array(
		'#type' => 'checkbox', 
		'#required' => true,
		'#title' => t('accept this student for watching next episode'),
		'#description' => t('Required. if this student has done his/her homeworks, check this option.'),
	);
	$form['uid'] = array(
		'#type' => 'hidden',
		'#value' => $uid,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('approve'),
	);
	return $form;
}

function student_confirmation_form_submit($form, &$form_state) {
	$user = user_load($form_state['values']['uid']);

	$node_query = "SELECT max(sn.field_sessionnumber_value) as session
        FROM field_data_field_siteinfo_stu main
        INNER JOIN field_data_field_instrument ins
        INNER JOIN field_data_field_levelnumber levn
        INNER JOIN field_data_field_sessionnumber sn
        ON main.field_siteinfo_stu_value = ins.entity_id
        AND main.field_siteinfo_stu_value = levn.entity_id
        AND main.field_siteinfo_stu_value = sn.entity_id
        WHERE main.entity_type = 'node'
        AND ins.field_instrument_value = :instrument
        AND levn.field_levelnumber_value = :level ";
		
	$user_query ="SELECT main.field_siteinfo_stu_value as field_id, ins.field_instrument_value as instrument, levn.field_levelnumber_value as level, sn.field_sessionnumber_value as session
        FROM field_data_field_siteinfo_stu main
        INNER JOIN field_data_field_instrument ins
        INNER JOIN field_data_field_levelnumber levn
        INNER JOIN field_data_field_sessionnumber sn
        ON main.field_siteinfo_stu_value = ins.entity_id
        AND main.field_siteinfo_stu_value = levn.entity_id
        AND main.field_siteinfo_stu_value = sn.entity_id
        WHERE main.entity_type = 'user'
        AND main.entity_id = :uid  
		ORDER BY `main`.`field_siteinfo_stu_value` DESC";
	
	$user_result = db_query($user_query, array(':uid' => $user->uid))->fetchObject();
	$node_result = db_query($node_query, array(':instrument' => $user_result->instrument, ':level' => $user_result->level))->fetchObject();

	if($user_result->session == $node_result->session){
		switch($user_result->level){
			case 'l1':
				$user_result->level = 'l2';
				break;
			case 'l2':
				$user_result->level = 'l3';
				break;
		}
		$user_result->session = 1;
	}else{
		$user_result->session = intval($user_result->session) + 1;		
	}
	add_collection($user , $user_result->instrument , $user_result->level , $user_result->session);
	drupal_set_message(t('Your approval successfully saved for student ') . $user->name, 'status');
}

function add_collection($user, $instrument , $level , $session) {
  module_load_include('inc', 'entity', 'includes/entity.controller');
  $values = array(
		'field_name' => 'field_siteinfo_stu',
		'field_instrument' => array(
			LANGUAGE_NONE => array(array('value' => $instrument)),
		),
		'field_levelnumber' => array(
			LANGUAGE_NONE => array(array('value' => $level)),
		),
		'field_sessionnumber' => array(
			LANGUAGE_NONE => array(array('value' => $session)),
		),
  );
  $entity = entity_create('field_collection_item', $values);
  $entity->setHostEntity('user', $user);
  $entity->save();
  
  //for giving user file access 
  if (!defined('FILE_ACCESS_USER')) {
    define('FILE_ACCESS_USER', 1);
  }

	$sql = "
		SELECT main.entity_id as nid 
        FROM field_data_field_siteinfo_stu main
        INNER JOIN field_data_field_instrument ins ON main.field_siteinfo_stu_value = ins.entity_id
        INNER JOIN field_data_field_levelnumber levn ON main.field_siteinfo_stu_value = levn.entity_id
        INNER JOIN field_data_field_sessionnumber sn ON main.field_siteinfo_stu_value = sn.entity_id
        WHERE main.entity_type = 'node' 
        AND ins.field_instrument_value = :instrument
        AND levn.field_levelnumber_value = :level
        AND sn.field_sessionnumber_value = :session" ;
	$result = db_query($sql, array(
		':instrument' =>$instrument,
		':level' =>$level,
		':session' =>$session
	));
	
	if($rows = $result->fetchAll()){
		foreach($rows as $row){
			$node = node_load($row->nid);
			if(isset($node->field_course_film['und'][0])){
				if(function_exists('file_access_set_file_access')){
					file_access_set_file_access($node->field_course_film['und'][0]['fid'] , $user->uid , NULL , FILE_ACCESS_USER);
				}else{
					drupal_set_message('خطایی در تایید هنرجو رخ داده است. لطفا با مدیریت تماس بگیرید.','error');
				}
			}
		}
	}
}

function which_teacher($value){
	return instrument_info('persian_name', $value, array('ostad_uid'), 'online');
}

function which_teacher_name($value){
	return instrument_info('name', $value, array('ostad_uid'), 'online');
}

function which_instrument($value){
	return instrument_info('persian_name', $value, array('name'), 'online');
}

function which_teacher_key($value){
	return instrument_info('oid', $value, array('ostad_uid'), 'online');
}

function which_instrument_key($value){
	return instrument_info('oid', $value, array('name'), 'online');
}

/*
 * returns uid of teachers by option ids of attribute 5
 */
function which_teacher_by_TeacherOptionId($value){
	return instrument_info('Teacher_OptionId', $value, array('ostad_uid'), 'online');
}

/**
 * Implements hook_menu().
 */
function uc_user_menu() {
  $items['node_reference_4fasl/autocomplete'] = array(
    'page callback' => 'node_reference_autocomplete_4fasl',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function student_node_refrence_form($form, &$form_state, $uid) {
	if (!is_array($form)) {
		$form = array();
	}
	$era_query_settings = array(array('type', 'course', '='));
	global $user;
	if(!isset($user->roles[3])){ //admin role id
		if($user->uid == 164 || $user->uid == 111){
			$era_query_settings[] = array('uid', array(111,164), 'IN');			
		}else{
		$era_query_settings[] = array('uid', $user->uid, '=');
		}
	}

	//we attach user id to remove items that were already sent
  $era_query_settings[] = array('uid', $uid, '!=');

	$form['refrenced_node'] = array(
		'#type' => 'entityreference', 
		'#required' => true,
		'#title' => 'تیتر محتوا',
		'#era_entity_type' => 'node',
        '#era_query_settings' => array(
            'limit' => 10,
            'property_conditions' => $era_query_settings,
/*          'field_conditions' => array(
				array('nid', 'title'),
            ),	 */		
		),
	);
	$form['uid'] = array(
		'#type' => 'hidden',
		'#value' => $uid,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('approve'),
	);
	return $form;
}

function student_node_refrence_form_submit($form, &$form_state) {
	$node = node_load($form_state['values']['refrenced_node']['entity_id']);
	$user = user_load($form_state['values']['uid']);
	$index = 0;
	if(isset($user->field_node_refrence['und'][0]['nid'])){
		$field_node_refrence = $user->field_node_refrence;
		$index = sizeof($user->field_node_refrence['und']);
	}
	$field_node_refrence['und'][$index]['nid'] =  $node->nid;
	$user->field_node_refrence = $field_node_refrence;
	if(user_save($user, array('field_node_refrence' => $field_node_refrence)) ){
		//adding access to view file
		if(isset($node->field_course_film['und'][0]) && function_exists('file_access_set_file_access')){
			file_access_set_file_access($node->field_course_film['und'][0]['fid'] , $user->uid , NULL , 1 /*FILE_ACCESS_USER*/);
		}else{
			drupal_set_message('خطایی در دسترسی فیلم های ارسالی به هنرجو رخ داده است. لطفا با مدیریت تماس بگیرید.','error');
		}
		drupal_set_message('فیلم مورد نظر به کاربر ارسال شد');

	}else{
		drupal_set_message("خطایی رخ داده است.", 'error');
	}
}

